### ISSUE TITLE
Wrong seconds with a TimeControl example

### ISSUE THREAD

**Issue by rafacouto** [mliebelt/pgn-spec-commented#16]
At [_TimeControl_ tag](https://github.com/mliebelt/pgn-spec-commented/blob/main/pgn-specification.md#961-tag-timecontrol) about the _fifth TimeControl field_, it's said that 

> an incremental time control of **90 minutes** plus one extra minute per move would be given by "**4500**+60"

It should be "5400+60" (90 minutes are 5400 seconds), shouldn't be?

**Comment by mliebelt** [comment]
Yes, you are right, I will correct that when I am online again (with my computer).

**Comment by mliebelt** [comment]
just checked, it is contained in the original spec 😁
